---
title: "Replication and Extension"
subtitle: "PLSC 501, spring 2025"
author: "Dave Clark"
institute: "Binghamton University"
date: today
date-format: long
format: 
  html: default
---

```{r setup, include=FALSE, echo=FALSE}

# knitr::opts_chunk$set(fig.retina = 2, fig.align = "center", warning=FALSE, error=FALSE, message=FALSE) 

# library(knitr)
# library(datasets)
library(tidyverse)
library(ggplot2)
# library(haven) #read stata w/labels
# library(countrycode)
library(patchwork)
# library(mvtnorm)
# library(modelsummary)
# library("GGally")
# library(stargazer)

```

# Replication & Extension project 

For the seminar, you need to replicate and extend a published paper. You should choose a paper based on two criteria - that the paper interests you; and that the data are available. Please do not choose based on familiarity or on the type of model - most of the papers you read will use nonlinear models, and that's completely fine. I'll help you with estimation/interpretation to the extent you need it.  

What should be in the paper, and what should the paper look like? Below, I list things you should consider and cover.

## Evaluating the paper

  - What is the paper about? Explain what the paper attempts to do, where it sits in the literature, and what it finds.
  
  - Why is the paper important (relatedly, why did it get published)? What does it contribute to knowledge in the field? What do we know from this paper we didn't know before? 
  
  - Are there any data or model innovations? If so, describe? 
 
  - What's the biggest problem or shortcoming of the paper? Why do you think this is problematic? Alternatively, what interesting questions do you think remain unanswered (that you'd like to try to answer)? Part of this is likely to be the motive for your extension.
 
  - What are you going to do to extend the paper? Why? What's your argument regarding why we need to change, augment, extend this paper? 
  
  - How are you going to extend the paper (ie, what do you need to do in terms of data, model, etc.)? 


## Replication

  -  Are you able to replicate the findings in the paper? Describe any issues you have doing this, issues in code, data etc.
 
  - Examining the data, do you see any potential issues the author(s) faced (or neglected)? Do you see problems in the data? Do you see problems in how the author(s) treated the data or estimated the model?


## Extension

This is the most important part of the project - take ownership of your argument; lay out the causal mechanism you imagine at work here, and argue for why this is a step forward that advances what we know in this field. How does your argument improve the state of knowledge in this field? 

  -  Make an argument, state a hypothesis.
 
  - Explain how you're going to test that hypothesis; what data do you need, what do you need to do.
  
  -  Estimate and interpret that model, and report quantities of interest. 
 
  - Explain your findings, and why this is important.


## Poster

  Create a poster presenting the original paper's argument, your extension and its rationale, your hypothesis, model, and findings. We'll present these in a poster session at the end of the semester. Treats will be provided! 





